#!/usr/bin/env ruby
# vim: ft=ruby
require 'mru/fuf'
require 'optparse'
opt = OptionParser.new
@opts = {
  type:  ENV['MRU_FUF_TYPE']  || Mru::Fuf::ITEMS,
  limit: ENV['MRU_FUF_LIMIT'].to_i || 1000,
}
opt.on('-t type', "--type=#{Mru::Fuf.types.join(",")}") {|v| @opts[:type] = v }
opt.on('-l num', "--limit=1000") {|v| @opts[:limit] = v.to_i }
opt.on('-r', '--reverse') {|v| @opts[:reverse] = true }
opt.parse!(ARGV)

puts Mru::Fuf::Data.load(
  @opts[:type],
  limit: @opts[:limit],
  reverse: @opts[:reverse]
).join("\n")
